// <auto-generated />
using MVC_Sample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCSample.Migrations
{
    [DbContext(typeof(CardioMachineContext))]
    [Migration("20190621012356_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_Sample.Models.CardioMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MachineModel");

                    b.Property<int>("MachineNumber");

                    b.Property<string>("MachineType");

                    b.Property<int>("capabilities1");

                    b.Property<int>("capabilities2");

                    b.Property<int>("capabilities3");

                    b.Property<int>("capabilities4");

                    b.Property<int>("capabilities5");

                    b.HasKey("Id");

                    b.ToTable("CardioMachine");
                });
#pragma warning restore 612, 618
        }
    }
}
